stages:
  - docker-build
  - docker-push
  - deploy


docker-build:
  stage: docker-build
  only:
    - master
  script:
    - docker build -t $DOCKER_REGISTER_HOST/wuruiwm/my_admin:latest -f docker/Dockerfile .


docker-push:
  stage: docker-push
  only:
    - master
  script:
    - docker login $DOCKER_REGISTER_HOST -u $DOCKER_REGISTER_USERNAME -p $DOCKER_REGISTER_PASSWORD
    - docker push $DOCKER_REGISTER_HOST/wuruiwm/my_admin:latest


deploy:
  stage: deploy
  only:
    - master
  script:
    - sshpass -p ${K8S_MASTER_PASSWORD} ssh -p ${K8S_MASTER_PORT} -o StrictHostKeyChecking=no ${K8S_MASTER_USERNAME}@${K8S_MASTER_HOST} "kubectl rollout restart -n my deployment my-admin"
